name    'puppet-bind'
version '0.0.1'
author  'Felipe openglx Zanchet Grazziotin'
license 'Apache2'
project_page 'https://github.com/openglx/pupet-bind'
source  'https://github.com/openglx/puppet-bind'
summary 'Puppet module for bind with views support'
description 'This module installs and manages bind. Check README.rdoc for details. Puppi is required for some common functions: you can install them without using the whole module. Monitor and firewall dependencies are needed only if the relevant features are enabled. This module is a fork from lermit code which adds DNS views support.'
dependency 'lab42/puppi', '>= 2.0.0'
dependency 'lab42/monitor', '>= 2.0.0'
dependency 'lab42/firewall', '>= 2.0.0'
